version: "3.0"
services:
  db:
    container_name: "db_telebot_current_rate"
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telebot_current_rate
    ports:
      - "5434:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge